models/client.py
from utils.db import db


class Client(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(100))
    last_name = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))
    age = db.Column(db.Integer)
    country = db.Column(db.String(100))

    def __init__(self, first_name, last_name, email, phone, age, country):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.phone = phone
        self.age = age
        self.country = country

models/user.py
from utils.db import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    email = db.Column(db.String(100))
    password = db.Column(db.String(100))

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from routes.clients import clients
from routes.users import users
import firebase_admin
from firebase_admin import credentials

app = Flask(__name__)

app.secret_key = 'Secret_Key'
# app.config["SQLALCHEMY_DATABASE_URI"] = "mysql://root:Juan123*@localhost/usersdb" MySQL
# app.config["SQLALCHEMY_DATABASE_URI"] = "mssql+pyodbc://JUANNARVAEZ\SQLEXPRESS/usersdb"
app.config["SQLALCHEMY_DATABASE_URI"] = "mssql+pyodbc://JUANNARVAEZ\SQLEXPRESS/usersdb?driver=ODBC+Driver+17+for+SQL+Server"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
SQLAlchemy(app)


app.register_blueprint(clients)
app.register_blueprint(users)

routes/clients.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from middlewares.middleware import check_token
from utils.validator import RegistrationClientForm, RegistrationClientsFileForm
from models.client import Client
from utils.db import db
import io
import csv

clients = Blueprint("clients", __name__)

# Vistas


@clients.route("/", methods=["GET", "POST"])
@check_token
def home():

    form = RegistrationClientForm()
    form_file = RegistrationClientsFileForm()

    if form.validate_on_submit() and form.submit.data:
        try:
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            phone = form.phone.data
            age = form.age.data
            country = form.country.data

            new_client = Client(first_name, last_name,
                                email, phone, int(age), country)

            db.session.add(new_client)
            db.session.commit()

            flash("Cliente guardado exitosamente", "success")

            return redirect(url_for("clients.home"))

        except:
            flash("Hubo un error al intentar guardar clientes, por favor revise informacion suministrada", "danger")

    if form_file.validate_on_submit() and form_file.submit_file.data:
        try:
            file = form_file.file.data
            stream = io.StringIO(
                file.stream.read().decode("UTF8"), newline=None)
            csv_input = csv.reader(stream)

            iter = 0
            for row in csv_input:
                if iter != 0:
                    first_name, last_name, email, phone, age, country = row
                    new_client = Client(
                        first_name, last_name, email, phone, int(age), country)

                    db.session.add(new_client)
                iter += 1

            print(csv_input)
            db.session.commit()

            flash("Clientes guardados exitosamente", "success")
            return redirect(url_for("clients.home"))

        except:
            flash("Hubo un error al intentar guardar clientes, por favor revise informacion suministrada", "danger")

    return render_template("index.html", form=form, form_file=form_file)


@clients.route("/clients")
@check_token
def list_clients():
    total_clients = Client.query.all()

    return render_template("clients.html", clients=total_clients)

# Consultas


@clients.route("/update_client/<id>", methods=["POST", "GET"])
@check_token
def modify_client(id):
    client_found = Client.query.get(id)
    if request.method == "POST":

        print("ID FROM POST")

        client_found.first_name = request.form["first_name"]
        client_found.last_name = request.form["last_name"]
        client_found.email = request.form["email"]
        client_found.phone = request.form["phone"]
        client_found.age = request.form["age"]
        client_found.country = request.form["country"]

        db.session.commit()

        flash("Cliente actualizado exitosamente")

        return redirect(url_for("clients.list_clients"))
    return render_template("update.html", client=client_found)


@clients.route("/delete_client/<id>")
@check_token
def remove_client(id):
    client_to_delete = Client.query.get(id)
    db.session.delete(client_to_delete)
    db.session.commit()

    flash("Cliente eliminado exitosamente")

    return redirect(url_for("clients.list_clients"))

routes/users.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, make_response
from utils.generate_token import generate_token
from utils.validator import RegistrationUserForm, LoginUserForm
from models.user import User
from utils.db import db
import pyrebase
import firebase_admin
from firebase_admin import credentials
import json

users = Blueprint("users", __name__)

firebase = pyrebase.initialize_app(json.load(open("fbconfig.json")))
auth = firebase.auth()


@users.route("/signup", methods=["GET", "POST"])
def signup():

    if request.cookies.get('token'):
        return redirect(url_for("clients.home"))

    form = RegistrationUserForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        try:
            user = auth.create_user_with_email_and_password(email, password)
            user_info = auth.sign_in_with_email_and_password(email, password)
            token = user_info['idToken']

            flash("Usuario creado satisfactoriamente!", "success")

            print(token)
            resp = make_response(redirect("/"))
            resp.set_cookie('token', token)

            return resp

        except:
            print('Error creating user')
            return render_template("register.html", form=form)

    else:
        return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if request.cookies.get('token'):
        return redirect(url_for("clients.home"))

    form = LoginUserForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        try:
            user = auth.sign_in_with_email_and_password(email, password)

            token = user['idToken']

            resp = make_response(redirect("/"))
            resp.set_cookie('token', token)

            flash("Bienvenido!", "success")
            return resp
        except:
            flash("Ingreso fallido, credenciales incorrectas", "danger")
            return render_template("login.html", form=form)

    return render_template("login.html", form=form)


@users.route("/logout", methods=["GET", "POST"])
def delete_cookie():
    resp = make_response(redirect("/login"))
    resp.delete_cookie("token")

    return resp

templates/clients.html
{% extends 'layout.html' %}

{% include('partials/_nav.html') %}

{% block content %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show alert-fixed position-fixed top-0 start-50 translate-middle-x" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>   
        {% endfor %}
    {% endif %}
{% endwith %}
<table class="table table-secondary table-hover mt-5">
    <thead>
        <tr>
            <td>Nombres</td>
            <td>Apellidos</td>
            <td>Correo electronico</td>
            <td>Telefono</td>
            <td>Edad</td>
            <td>Pais</td>
            <td>Acciones</td>
        </tr>
    </thead>
    <tbody>
        {% for client in clients%}
            <tr class="mx-2">
                <td>{{client.first_name}}</td>
                <td>{{client.last_name}}</td>
                <td>{{client.email}}</td>
                <td>{{client.phone}}</td>
                <td>{{client.age}}</td>
                <td>{{client.country}}</td>
                <td>
                    <a href="{{ url_for("clients.modify_client", id=client.id) }}"><i class="fa-solid fa-pencil fa-lg text-secondary me-3"></i></a>
                    <a href="{{ url_for("clients.remove_client", id=client.id) }}"><i class="fa-solid fa-xmark fa-xl text-danger"></i></a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% include('partials/_nav.html') %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{category}} alert-dismissible fade show alert-fixed position-fixed top-0 start-50 translate-middle-x" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>  
        {% endfor %}
    {% endif %}
{% endwith %}
    
    
<div class="row mt-5">
    <div class="col-md-10 col-lg-6 offset-md-1 offset-lg-3">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active link-danger" id="form-tab" data-bs-toggle="tab" data-bs-target="#form" type="button" role="tab" aria-controls="form" aria-selected="true">Formulario</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link link-danger" id="load-tab" data-bs-toggle="tab" data-bs-target="#load" type="button" role="tab" aria-controls="load" aria-selected="false">Cargar CSV</button>
            </li>
          </ul>
          <div class="tab-content border-start border-end border-bottom rounded-bottom p-5" id="myTabContent">
            <div class="tab-pane fade show active" id="form" role="tabpanel" aria-labelledby="form-tab">
                <form action="" method="POST">
                    {{ form.hidden_tag() }}
                    <div class="form-floating mb-3">
                        {% if form.first_name.errors %}
                            {{ form.first_name(class="form-control is-invalid", placeholder="Nombres", id="first_name") }}
                            {{ form.first_name.label(for="first_name", content="Nombres") }}
                            <div class="invalid-feedback">
                                {% for error in form.first_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.first_name(class="form-control", placeholder="Nombres", id="first_name") }}
                            {{ form.first_name.label(for="first_name", content="Nombres") }}
                        {% endif %}

                    </div>
                    <div class="form-floating mb-3">
                        {% if form.last_name.errors %}
                            {{ form.last_name(class="form-control is-invalid", placeholder="Apellidos", id="last_name") }}
                            {{ form.last_name.label(for="last_name", content="Apellidos") }}
                            <div class="invalid-feedback">
                                {% for error in form.last_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.last_name(class="form-control", placeholder="Apellidos", id="last_name") }}
                            {{ form.last_name.label(for="last_name", content="Apellidos") }}
                        {% endif %}

                    </div>
                    <div class="form-floating mb-3">
                        {% if form.email.errors %}
                            {{ form.email(class="form-control is-invalid", placeholder="Correo", id="email") }}
                            {{ form.email.label(for="email", content="Correo") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control", placeholder="Correo", id="email") }}
                            {{ form.email.label(for="email", content="Correo") }}
                        {% endif %}

                    </div>
                    <div class="form-floating mb-3">
                        {% if form.phone.errors %}
                            {{ form.phone(class="form-control is-invalid", placeholder="Telefono", id="phone") }}
                            {{ form.phone.label(for="phone", content="Telefono") }}
                            <div class="invalid-feedback">
                                {% for error in form.phone.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.phone(class="form-control", placeholder="Telefono", id="phone") }}
                            {{ form.phone.label(for="phone", content="Telefono") }}
                        {% endif %}

                    </div>
                    <div class="form-floating mb-3">
                        {% if form.age.errors %}
                            {{ form.age(class="form-control is-invalid", placeholder="Edad", id="age") }}
                            {{ form.age.label(for="age", content="Edad") }}
                            <div class="invalid-feedback">
                                {% for error in form.age.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.age(class="form-control", placeholder="Edad", id="age") }}
                            {{ form.age.label(for="age", content="Edad") }}
                        {% endif %}

                    </div>
                    <div class="form-floating mb-3">
                        {% if form.country.errors %}
                            {{ form.country(class="form-control is-invalid", placeholder="Country", id="country") }}
                            {{ form.country.label(for="country", content="Country") }}
                            <div class="invalid-feedback">
                                {% for error in form.country.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.country(class="form-control", placeholder="Country", id="country") }}
                            {{ form.country.label(for="country", content="Country") }}
                        {% endif %}

                    </div>
                    {{ form.submit(class="btn btn-danger mt-2") }}
                    <!--<div class="form-floating mb-3">
                        <input type="text" id="first_name" name="first_name" placeholder="Nombres" class="form-control">
                        <label for="first_name">Nombres</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" id="last_name" name="last_name" placeholder="Apellidos" class="form-control">
                        <label for="last_name">Apellidos</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" id="email" name="email" placeholder="Email" class="form-control">
                        <label for="email">Correo electronico</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" id="phone" name="phone" placeholder="Teléfono" class="form-control">
                        <label for="phone">Telefono</label>
                    </div>
                    
                    <button class="btn btn-danger mt-2">Guardar</button>-->
                </form>
            </div>
            <div class="tab-pane fade" id="load" role="tabpanel" aria-labelledby="load-tab">

                <form action="" method="POST" enctype="multipart/form-data">
                    {{ form_file.hidden_tag() }}
                    <div class="mb-2">
                        {% if form_file.file.errors %}
                            {{ form_file.file(class="form-control is-invalid", placeholder="Archivo", id="file") }}

                            <div class="invalid-feedback">
                                {% for error in form_file.file.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form_file.file(class="form-control", placeholder="Archivo", id="file") }}
                            
                        {% endif %}

                        <!--<input type="file" name="csv_file" placeholder="Archivo" class="form-control" id="csv_file" accept=".csv">
                        <label for="file" class="form-label"></label>-->
                    </div>
                    {{ form_file.submit_file(class="btn btn-danger mt-2", accept=".csv") }}
                    <!--<button class="btn btn-danger">Cargar</button>-->
                </form>
            </div>
          </div>
    </div>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/static/icons/logo.ico" type="image/x-icon">
    <title>Derco Project - User Registry</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" integrity="sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="/static/styles/styles.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body class="min-vh-100 position-relative">
    <div class="container p-5">
        {% block content %}

        {% endblock %}
    </div>
    {% include('partials/_footer.html') %}
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{category}} alert-dismissible fade show alert-fixed position-fixed top-0 start-50 translate-middle-x" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>  
        {% endfor %}
    {% endif %}
{% endwith %}
<div class="container-content">
    <div class="container-login">
        <div class="row mt-5">
            <div class="col-12 col-md-4 offset-4 text-center">
                <img src="/static/images/logo.png" class="logo" alt="logo_derco" />
            </div>
        </div> 
        <div class="row mt-3">
            <div class="col-12 col-md-6 offset-3 text-center">
                <h3>Ingreso Usuarios</h1>
            </div>
        </div>  
        <div class="row mt-3">
            <div class="col-md-10 col-lg-6 offset-md-1 offset-lg-3 text-center">
                <form action="" method="POST">
                    {{ form.hidden_tag() }}
                        <div class="form-floating mb-3">
                            {% if form.email.errors %}
                                {{ form.email(class="form-control is-invalid", placeholder="Correo", id="email") }}
                                {{ form.email.label(for="email", content="Correo") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control", placeholder="Correo", id="email") }}
                                {{ form.email.label(for="email", content="Correo") }}
                            {% endif %}
        
                        </div>
                        <div class="form-floating mb-3">
                            {% if form.password.errors %}
                                {{ form.password(class="form-control is-invalid", placeholder="Contrasena", id="password") }}
                                {{ form.password.label(for="password", content="Contrasena") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor%}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control", placeholder="Contrasena", id="password") }}
                                {{ form.password.label(for="password", content="Contrasena") }}
                            {% endif %}
        
                        </div>
                        {{ form.submit(class="btn btn-danger mt-2") }}
                </form>
            </div>
            
        </div>
        <div class="row mt-5">
            <div class="col-md-6 col-lg-4 offset-md-3 offset-lg-4 p-1 text-center">
                <small class="text-muted">
                    No tienes cuenta? Registrate <a href="{{ url_for("users.signup")}}">aqui</a>
                </small>
            </div>
        </div>
        
    </div>
</div>


{% endblock %}

templates/partials/_footer.html
<div class="position-absolute bg-dark text-light w-100 bottom-0">
    <p class="m-3 text-center">Bluesmile Technology - 2022</p>
</div>

templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container">
      <a class="navbar-brand" href="/">DERCO Registro de clientes</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for("clients.list_clients")}}">Clientes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for("users.delete_cookie")}}">Salir</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

templates/register.html
{% extends 'layout.html' %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{category}} alert-dismissible fade show alert-fixed position-fixed top-0 start-50 translate-middle-x" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>  
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="container-content">
    <div class="container-login">
        <div class="row mt-3">
            <div class="col-12 col-md-4 offset-4 text-center">
                <img src="/static/images/logo.png" class="logo" alt="logo_derco" />
            </div>
        </div> 
        <div class="row mt-3">
            <div class="col-12 col-md-6 offset-3 text-center">
                <h3>Registro Usuarios</h1>
            </div>
        </div>  
    
        <div class="row mt-3">
            <div class="col-md-10 col-lg-6 offset-md-1 offset-lg-3 text-center">
                <form action="" method="POST">
                    {{ form.hidden_tag() }}
                        <div class="form-floating mb-3">
                            
                            {% if form.username.errors %}
                                {{ form.username(class="form-control is-invalid", placeholder="Usuario", id="username") }}
                                {{ form.username.label(for="username", content="Usuario") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{error}}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control", placeholder="Usuario", id="username") }}
                                {{ form.username.label(for="username", content="Usuario") }}
                            {% endif %}

                        </div>
                        <div class="form-floating mb-3">
                            {% if form.email.errors %}
                                {{ form.email(class="form-control is-invalid", placeholder="Correo", id="email") }}
                                {{ form.email.label(for="email", content="Correo") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control", placeholder="Correo", id="email") }}
                                {{ form.email.label(for="email", content="Correo") }}
                            {% endif %}

                        </div>
                        <div class="form-floating mb-3">
                            {% if form.password.errors %}
                                {{ form.password(class="form-control is-invalid", placeholder="Contrasena", id="password") }}
                                {{ form.password.label(for="password", content="Contrasena") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor%}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control", placeholder="Contrasena", id="password") }}
                                {{ form.password.label(for="password", content="Contrasena") }}
                            {% endif %}

                        </div>
                        {{ form.submit(class="btn btn-danger mt-2") }}
                </form>
            </div>
            
        </div>
        <div class="row mt-5">
            <div class="col-md-6 col-lg-4 offset-md-3 offset-lg-4 p-1 text-center">
                <small class="text-muted">
                    Te encuentras registrado? Ingresa <a href="{{ url_for("users.login")}}">aqui</a>
                </small>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/update.html
{% extends 'layout.html' %}

{% include('partials/_nav.html') %}

{% block content %}

    <div class="row mt-5">
        <div class="col-md-10 col-lg-6 offset-md-1 offset-lg-3">
            <form action="/update_client/{{client.id}}" method="POST">
                <div class="form-floating mb-3">
                    <input type="text" id="new_first_name" name="first_name" placeholder="Nombres" class="form-control" value="{{client.first_name}}">
                    <label for="new_first_name">Nombres</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" id="new_last_name" name="last_name" placeholder="Apellidos" class="form-control" value="{{client.last_name}}">
                    <label for="new_last_name">Apellidos</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" id="new_email" name="email" placeholder="Email" class="form-control" value="{{client.email}}">
                    <label for="new_email">Correo electronico</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" id="new_phone" name="phone" placeholder="Teléfono" class="form-control" value="{{client.phone}}">
                    <label for="new_phone">Telefono</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" id="new_age" name="age" placeholder="Edad" class="form-control" value="{{client.age}}">
                    <label for="new_age">Edad</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="text" id="new_country" name="country" placeholder="Pais" class="form-control" value="{{client.country}}">
                    <label for="new_country">Pais</label>
                </div>
                
                <button class="btn btn-danger">Guardar</button>
            </form>
        </div>
    </div>

{% endblock %}